Isen.DotNet.Projet.Web/Models/ErrorViewModel.cs
using System;

namespace Isen.DotNet.Projet.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Isen.DotNet.Projet.Web/Controllers/AdresseController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Isen.DotNet.Projet.Web.Models;
using Isen.DotNet.Projet.Library.Repository.Interfaces;
using Isen.DotNet.Projet.Library.Repository.InMemory;
using Isen.DotNet.Projet.Library.Models.Implementation;
using Microsoft.Extensions.Logging;

namespace Isen.DotNet.Projet.Web.Controllers
{
    public class AdresseController : BaseController<Adresse>
    {
        public AdresseController(IAdresseRepository repository) : base(repository)
        {
        }
    }
}

Isen.DotNet.Projet.Web/Controllers/CategorieController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Isen.DotNet.Projet.Web.Models;
using Isen.DotNet.Projet.Library.Repository.Interfaces;
using Isen.DotNet.Projet.Library.Repository.InMemory;
using Isen.DotNet.Projet.Library.Models.Implementation;
using Microsoft.Extensions.Logging;

namespace Isen.DotNet.Projet.Web.Controllers
{
    public class CategorieController : BaseController<Categorie>
    {
        public CategorieController(ICategorieRepository repository) : base(repository)
        {
        }
    }
}

Isen.DotNet.Projet.Web/Controllers/CommuneController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Isen.DotNet.Projet.Web.Models;
using Isen.DotNet.Projet.Library.Repository.Interfaces;
using Isen.DotNet.Projet.Library.Repository.InMemory;
using Isen.DotNet.Projet.Library.Models.Implementation;
using Microsoft.Extensions.Logging;

namespace Isen.DotNet.Projet.Web.Controllers
{
    public class CommuneController : BaseController<Commune>
    {
        public CommuneController(ICommuneRepository repository) : base(repository)
        {
        }
    }
}

Isen.DotNet.Projet.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Isen.DotNet.Projet.Web.Models;

namespace Isen.DotNet.Projet.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Isen.DotNet.Projet.Web/Controllers/PIController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Isen.DotNet.Projet.Web.Models;
using Isen.DotNet.Projet.Library.Repository.Interfaces;
using Isen.DotNet.Projet.Library.Repository.InMemory;
using Isen.DotNet.Projet.Library.Models.Implementation;
using Microsoft.Extensions.Logging;

namespace Isen.DotNet.Projet.Web.Controllers
{
    public class PIController : BaseController<PI>
    {
        public PIController(IPIRepository repository) : base(repository)
        {
        }
    }
}

Isen.DotNet.Projet.Web/Controllers/_BaseController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Isen.DotNet.Projet.Web.Models;
using Isen.DotNet.Projet.Library.Repository.Interfaces;
using Isen.DotNet.Projet.Library.Repository.InMemory;
using Isen.DotNet.Projet.Library.Models.Implementation;
using Microsoft.Extensions.Logging;
using Isen.DotNet.Projet.Library.Models.Base;

namespace Isen.DotNet.Projet.Web.Controllers
{
    public abstract partial class BaseController<T> : Controller
        where T : BaseModel
    {
        protected IBaseRepository<T> _repository;
        protected readonly ILogger<BaseController<T>> _logger;

        public BaseController(IBaseRepository<T> repository)
        {
            _repository = repository;
        }

        public virtual IActionResult Index()
        {            
            var model = _repository.GetAll();
            return View(model);
        }

        public virtual IActionResult Detail(int? id)
        {
            // Pas d'id > form vide (création)
            if (id == null) return View();
            // Récupérer la ville et la passer à la vue
            var model = _repository.Single(id.Value);
            return View(model);
        }

        [HttpPost]
        public virtual IActionResult Detail(T model)
        {
            _repository.Update(model);
            _repository.Save();
            return RedirectToAction("Index");
        }

        public virtual IActionResult Delete(int? id)
        {
            if (id != null)
            {
                _repository.Delete(id.Value);
                _repository.Save();
            }
            return RedirectToAction("Index");
        }
    }
}

Isen.DotNet.Projet.Web/Views/Adresse/Detail.cshtml
@using Isen.DotNet.Projet.Library.Models.Implementation;

@using Isen.DotNet.Projet.Library.Repository.Interfaces;
@{
    ViewData["Title"] = "Adresse (détail)";
}
@inject ICommuneRepository _communeRepository;
@model Adresse

<div class="row">
    <div class="col-md-12">
        <h1>Adresse <small>/Adresse/detail</small></h1>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <form class="form-horizontal" asp-action="Detail">
            <input type="hidden" value="@Model?.Id" asp-for="Id" />
            <div>
                <label for="Nom" class="control-label">Nom de l'Adresse :</label>
                <input type="text" class="form-control"
                    id="Nom" placeholder="Nom de l'Adresse'"
                    value="@Model?.Nom" asp-for="Nom" />
            </div>
            <br />
            <div>
                <label for="CodePostal" class="control-label">Code Postal de l'Adresse :</label>
                <input type="long" class="form-control"
                    id="CodePostal" placeholder="Code Postal de l'Adresse"
                    value="@Model?.CodePostal" asp-for="CodePostal" />
            </div>

            <br />

            <div>
                <label for="CommuneID">
                    Commune : 
                </label>
                @Html.DropDownListFor(
                    p => p.CommuneID,
                    new SelectList(
                        _communeRepository.GetAll(), 
                        "Id", 
                        "Nom"),
                    "<Sélectionnez une commune>",
                    new { @class = "form-control" })
            </div>

            <br />
            <div>
                <label for="Lattitude" class="control-label">Lattitude de l'Adresse :</label>
                <input type="text" class="form-control"
                    id="Lattitude" placeholder="Lattitude de l'Adresse"
                    value="@Model?.Lattitude" asp-for="Lattitude" />
            </div>
            <br />
            <div>
                <label for="Longitude" class="control-label">Longitude de l'Adresse :</label>
                <input type="text" class="form-control"
                    id="Longitude" placeholder="Longitude de l'Adresse"
                    value="@Model?.Longitude" asp-for="Longitude" />
            </div>
            <br />
            <br />
            <input type="submit" class="btn btn-primary" value="Valider" />
            <a class="btn btn-default" 
                asp-controller="Adresse" asp-action="Index">Annuler</a>
        </form>
    </div>
</div>

Isen.DotNet.Projet.Web/Views/Adresse/Index.cshtml
@using Isen.DotNet.Projet.Library.Models.Implementation;
@{
    ViewData["Title"] = "Adresse";
}
@model IEnumerable<Adresse>

<div class="row">
    <div class="col-md-12">
        <h1>Adresse <small>/Adresse/index</small></h1>
    </div>
</div>
<div class="row">
    <a class="btn btn-default" 
        asp-controller="Adresse" asp-action="Detail">Ajouter une adresse...</a>
</div>
<div class="row">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>Nom</th>
                <th>Code Postal</th>
                <th>Commune</th>
                <th>Lattitude</th>
                <th>Longitude</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var ad in Model)
            {
            <tr>
                <td>@ad.Id</td>
                <td>@ad.Nom</td>
                <td>@ad.CodePostal</td>
                <td>@ad.Commune?.Nom</td>
                
                <td>@ad.Lattitude</td>
                <td>@ad.Longitude</td>
                <td>
                    <a class="btn btn-default" asp-controller="Adresse" asp-action="Detail" asp-route-id="@ad.Id">Editer</a>
                    &nbsp;
                    <a class="btn btn-danger" asp-controller="Adresse" asp-action="Delete" asp-route-id="@ad.Id">Supprimer</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>

Isen.DotNet.Projet.Web/Views/Categorie/Detail.cshtml
@using Isen.DotNet.Projet.Library.Models.Implementation;
@{
    ViewData["Title"] = "Categorie (détail)";
}
@model Categorie

<div class="row">
    <div class="col-md-12">
        <h1>Catégorie <small>/categorie/detail</small></h1>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <form class="form-horizontal" asp-action="Detail">
            <input type="hidden" value="@Model?.Id" asp-for="Id" />
            <div>
                <label for="Nom" class="control-label">Nom de la catégorie :</label>
                <input type="text" class="form-control"
                    id="Nom" placeholder="Nom de la catégorie"
                    value="@Model?.Nom" asp-for="Nom" />
            </div>
            <br />
            <div>
                <label for="Descriptif" class="control-label">Descriptif de la catégorie :</label>
                <input type="double" class="form-control"
                    id="Descriptif" placeholder="Descriptif de la categorie"
                    value="@Model?.Descriptif" asp-for="Descriptif" />
            </div>
            <br />
            <input type="submit" class="btn btn-primary" value="Valider" />
            <a class="btn btn-default" 
                asp-controller="Categorie" asp-action="Index">Annuler</a>
        </form>
    </div>
</div>

Isen.DotNet.Projet.Web/Views/Categorie/Index.cshtml
@using Isen.DotNet.Projet.Library.Models.Implementation;
@{
    ViewData["Title"] = "Categorie";
}
@model IEnumerable<Categorie>

<div class="row">
    <div class="col-md-12">
        <h1>Categorie <small>/categorie/index</small></h1>
    </div>
</div>
<div class="row">
    <a class="btn btn-default" 
        asp-controller="Categorie" asp-action="Detail">Ajouter une categorie...</a>
</div>
<div class="row">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>Nom</th>
                <th>Descriptif</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var cat in Model)
            {
            <tr>
                <td>@cat.Id</td>
                <td>@cat.Nom</td>
                <td>@cat.Descriptif</td>
                <td>
                    <a class="btn btn-default" asp-controller="Categorie" asp-action="Detail" asp-route-id="@cat.Id">Editer</a>
                    &nbsp;
                    <a class="btn btn-danger" asp-controller="Categorie" asp-action="Delete" asp-route-id="@cat.Id">Supprimer</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>

Isen.DotNet.Projet.Web/Views/Commune/Detail.cshtml
@using Isen.DotNet.Projet.Library.Models.Implementation;
@{
    ViewData["Title"] = "Commune (détail)";
}
@model Commune

<div class="row">
    <div class="col-md-12">
        <h1>Commune <small>/commune/detail</small></h1>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <form class="form-horizontal" asp-action="Detail">
            <input type="hidden" value="@Model?.Id" asp-for="Id" />
            <div>
                <label for="Nom" class="control-label">Nom de la commune :</label>
                <input type="text" class="form-control"
                    id="Nom" placeholder="Nom de la commune"
                    value="@Model?.Nom" asp-for="Nom" />
            </div>
            <br />
            <div>
                <label for="Lattitude" class="control-label">Lattitude de la commune :</label>
                <input type="text" class="form-control"
                    id="Lattitude" placeholder="Lattitude de la commune"
                    value="@Model?.Lattitude" asp-for="Lattitude" />
            </div>
            <br />
            <div>
                <label for="Longitude" class="control-label">Longitude de la commune :</label>
                <input type="text" class="form-control"
                    id="Longitude" placeholder="Longitude de la commune"
                    value="@Model?.Longitude" asp-for="Longitude" />
            </div>
            <br />
            <br />
            <input type="submit" class="btn btn-primary" value="Valider" />
            <a class="btn btn-default" 
                asp-controller="Commune" asp-action="Index">Annuler</a>
        </form>
    </div>
</div>

Isen.DotNet.Projet.Web/Views/Commune/Index.cshtml
@using Isen.DotNet.Projet.Library.Models.Implementation;
@{
    ViewData["Title"] = "Commune";
}
@model IEnumerable<Commune>

<div class="row">
    <div class="col-md-12">
        <h1>Commune <small>/commune/index</small></h1>
    </div>
</div>
<div class="row">
    <a class="btn btn-default" 
        asp-controller="Commune" asp-action="Detail">Ajouter une commune...</a>
</div>
<div class="row">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>Nom</th>
                <th>Lattitude</th>
                <th>Longitude</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var com in Model)
            {
            <tr>
                <td>@com.Id</td>
                <td>@com.Nom</td>
                <td>@com.Lattitude</td>
                <td>@com.Longitude</td>
                <td>
                    <a class="btn btn-default" asp-controller="Commune" asp-action="Detail" asp-route-id="@com.Id">Editer</a>
                    &nbsp;
                    <a class="btn btn-danger" asp-controller="Commune" asp-action="Delete" asp-route-id="@com.Id">Supprimer</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>

Isen.DotNet.Projet.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
    //Layout = "_LayoutEmpty";
}
<div class="row">
    <div class="col-md-12">
        <h1>Home <small>/home/about</small></h1>
        <p>Ceci est le contenu de la vue Home, action About</p>
    </div>
</div>

Isen.DotNet.Projet.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<div class="row">
    <div class="col-md-12">
        <h1>Home <small>/home/contact</small></h1>
        <p>Ceci est le contenu de la vue Home, action Contact</p>
    </div>
</div>

Isen.DotNet.Projet.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
    ViewData["Desc"] = "Description longue du site";
    var urls = new List<string>
    {
        "http://localhost:5000/Home/Index",
        "http://localhost:5000/Home/About",
        "http://localhost:5000/Home/Contact"
    };
}
<div class="row">
    <div class="col-md-12">
        <h1>Home <small>/home/index</small></h1>
        <p>Ceci est le contenu de la vue Home, action Index</p>
    </div>
</div>
<div class="row">
    @foreach(var url in urls)
    {
        <div class="col-md-4 bg-info">
            <a href="@url">@url</a>
        </div>
    }
</div>

Isen.DotNet.Projet.Web/Views/PI/Detail.cshtml
@using Isen.DotNet.Projet.Library.Models.Implementation;
@using Isen.DotNet.Projet.Library.Repository.Interfaces;
@{
    ViewData["Title"] = "PI (détail)";
}
@inject IAdresseRepository _adresseRepository;

@inject ICategorieRepository _categorieRepository;
@model PI

<div class="row">
    <div class="col-md-12">
        <h1>PI <small>/PI/detail</small></h1>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <form class="form-horizontal" asp-action="Detail">
            <input type="hidden" value="@Model?.Id" asp-for="Id" />
            <div>
                <label for="Nom" class="control-label">Nom du PI :</label>
                <input type="text" class="form-control"
                    id="Nom" placeholder="Nom du PI"
                    value="@Model?.Nom" asp-for="Nom" />
            </div>
            <br />
            <div>
                <label for="Descriptif" class="control-label">Descriptif du PI :</label>
                <input type="text" class="form-control"
                    id="Descriptif" placeholder="Descriptif du PI"
                    value="@Model?.Descriptif" asp-for="Descriptif" />
            </div>

 <br />

            <div>
                <label for="CategorieID">
                    Categorie : 
                </label>
                @Html.DropDownListFor(
                    p => p.CategorieID,
                    new SelectList(
                        _categorieRepository.GetAll(), 
                        "Id", 
                        "Nom"),
                    "<Sélectionnez une categorie>",
                    new { @class = "form-control" })
            </div>

            <br />

            <div>
                <label for="AdresseID">
                    Adresse : 
                </label>
                @Html.DropDownListFor(
                    p => p.AdresseID,
                    new SelectList(
                        _adresseRepository.GetAll(), 
                        "Id", 
                        "Nom"),
                    "<Sélectionnez une adresse>",
                    new { @class = "form-control" })
            </div>

            <br />
            <br />
            <input type="submit" class="btn btn-primary" value="Valider" />
            <a class="btn btn-default" 
                asp-controller="PI" asp-action="Index">Annuler</a>
        </form>
    </div>
</div>

Isen.DotNet.Projet.Web/Views/PI/Index.cshtml
@using Isen.DotNet.Projet.Library.Models.Implementation;
@{
    ViewData["Title"] = "Point d'Intéret ";
}
@model IEnumerable<PI>

<div class="row">
    <div class="col-md-12">
        <h1>Point d'Intéret <small>/pi/index</small></h1>
    </div>
</div>
<div class="row">
    <a class="btn btn-default" 
        asp-controller="PI" asp-action="Detail">Ajouter un point d'interet...</a>
</div>
<div class="row">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>Nom</th>
                <th>Descriptif</th>
                <th>Catégorie</th>
                <th>Adresse</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var pi in Model)
            {
            <tr>
                <td>@pi.Id</td>
                <td>@pi.Nom</td>
                <td>@pi.Descriptif</td>
                <td>@pi.Categorie?.Nom</td>
                <td>@pi.Adresse?.Nom</td>
                <td>
                    <a class="btn btn-default" asp-controller="PI" asp-action="Detail" asp-route-id="@pi.Id">Editer</a>
                    &nbsp;
                    <a class="btn btn-danger" asp-controller="PI" asp-action="Delete" asp-route-id="@pi.Id">Supprimer</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>

Isen.DotNet.Projet.Web/Views/Shared/_Footer.cshtml
<hr />
<footer>
    <p>&copy; 2018 - Anthonioz Lisa & Rivière Loona</p>
</footer>

Isen.DotNet.Projet.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Isen.DotNet.Projet.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Isen.DotNet.Projet.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Isen.DotNet.Projet.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Isen.DotNet.Projet.Web/Views/Shared/_LayoutEmpty.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | @ViewData["Desc"] - myWebApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="container body-content">
        <!-- ViewStart est injecté ici -->
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Isen.DotNet.Projet.Web/Views/Shared/_Nav.cshtml
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">my<strong>Web</strong>App</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                <li class="dropdown">
                    <a href="#" 
                        class="dropdown-toggle"
                        data-toggle="dropdown"
                        role="button"
                        aria-haspopup="true"
                        aria-expanded="false">
                        Point d'Intéret
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a asp-controller="PI" asp-action="Index">Tous...</a></li>
                        <li><a asp-controller="PI" asp-action="Detail">Ajouter...</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" 
                        class="dropdown-toggle"
                        data-toggle="dropdown"
                        role="button"
                        aria-haspopup="true"
                        aria-expanded="false">
                        Communes
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a asp-controller="Commune" asp-action="Index">Toutes...</a></li>
                        <li><a asp-controller="Commune" asp-action="Detail">Ajouter...</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" 
                        class="dropdown-toggle"
                        data-toggle="dropdown"
                        role="button"
                        aria-haspopup="true"
                        aria-expanded="false">
                        Catégories
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a asp-controller="Categorie" asp-action="Index">Toutes...</a></li>
                        <li><a asp-controller="Categorie" asp-action="Detail">Ajouter...</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" 
                        class="dropdown-toggle"
                        data-toggle="dropdown"
                        role="button"
                        aria-haspopup="true"
                        aria-expanded="false">
                        Adresse
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a asp-controller="Adresse" asp-action="Index">Toutes...</a></li>
                        <li><a asp-controller="Adresse" asp-action="Detail">Ajouter...</a></li>
                    </ul>
                </li>
                <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
            </ul>
        </div>
    </div>
</nav>